version: "3.8"
services:
  client:
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    ports:
      - "80:3000"
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - type: bind
        source: ./client
        target: /app
      - type: volume
        target: /app/node_modules
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./api/src
        target: /app/src
    ports:
      - "3000:80"
      - "5678:5678"
      - "9229:9229"
  db:
    image: mongo
    volumes:
      - type: volume
        source: dbtest
        target: /data/db
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    depends_on:
      - api
      - db
volumes:
  dbtest:
